// Consistent icon system for the entire application
// Following the CLEAN and ORGANIZED principles
import {
    Brain,
    Heart,
    Users,
    Leaf,
    Rocket,
    MessageCircle,
    Home,
    User,
    Settings,
    Book,
    Target,
    TrendingUp,
    Calendar,
    Star,
    Zap,
    Check,
    X,
    Send,
    Bot,
    Activity,
    Mic,
    Volume2,
    StopCircle,
    Ellipsis,
    ChevronRight,
    MoreHorizontal,
    PanelLeft,
    ArrowRight,
    Sparkles,
    Family,
    Baby,
    UserPlus,
    Share2,
    Award,
    TrendingDown,
    AlertTriangle,
    RefreshCw,
    Copy,
    ArrowDown,
    Trash,
    Bell,
    Moon,
    Sun,
    Palette,
    Shield,
    Lock,
    Eye,
    EyeOff,
    Plus,
    Minus,
    Edit,
    Save,
    Upload,
    Download,
    Search,
    Filter,
    SortAsc,
    SortDesc,
    Grid,
    List,
    Clock,
    MapPin,
    Phone,
    Mail,
    Globe,
    Facebook,
    Twitter,
    Instagram,
    Youtube,
    Linkedin,
    Github,
    Slack,
    Discord,
    Whatsapp,
    Telegram,
    FileText,
    Image,
    Video,
    Music,
    Camera,
    Gift,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Euro,
    PoundSterling,
    IndianRupee,
    JapaneseYen,
    Wallet,
    Banknote,
    PiggyBank,
    TrendingUpDown,
    BarChart,
    PieChart,
    LineChart,
    Database,
    Server,
    Cloud,
    Wifi,
    Bluetooth,
    WifiOff,
    BluetoothOff,
    Battery,
    BatteryCharging,
    BatteryFull,
    BatteryLow,
    BatteryMedium,
    Power,
    PowerOff,
    Lightbulb,
    LightbulbOff,
    Fan,
    Thermometer,
    Droplets,
    Wind,
    SunDim,
    Sunset,
    Sunrise,
    MoonStar,
    Stars,
    CloudRain,
    CloudSnow,
    CloudLightning,
    CloudDrizzle,
    CloudFog,
    CloudHail,
    CloudRainWind,
    CloudSnowWind,
    CloudLightningRain,
    CloudOff,
    Cloudy,
    PartlyCloudy,
    Sunny,
    SunsetSunrise,
    ThermometerSun,
    ThermometerSnow,
    Waves,
    WavesLadder,
    WavesTop,
    WavesBottom,
    WavesMiddle,
    WavesLeft,
    WavesRight,
    WavesUp,
    WavesDown,
    WavesInOut,
    WavesLeftRight,
    WavesUpDown,
    WavesCircle,
    WavesSquare,
    WavesTriangle,
    WavesPentagon,
    WavesHexagon,
    WavesHeptagon,
    WavesOctagon,
    WavesStar,
    WavesDiamond,
    WavesHeart,
    WavesSpade,
    WavesClub,
    WavesPentagram,
    WavesHexagram,
    WavesHeptagram,
    WavesOctagram,
    WavesEnneagram,
    WavesDecagram,
    WavesCircleDashed,
    WavesSquareDashed,
    WavesTriangleDashed,
    WavesPentagonDashed,
    WavesHexagonDashed,
    WavesHeptagonDashed,
    WavesOctagonDashed,
    WavesStarDashed,
    WavesDiamondDashed,
    WavesHeartDashed,
    WavesSpadeDashed,
    WavesClubDashed,
    WavesPentagramDashed,
    WavesHexagramDashed,
    WavesHeptagramDashed,
    WavesOctagramDashed,
    WavesEnneagramDashed,
    WavesDecagramDashed,
} from "lucide-react";

// Agent-specific icons
export const AgentIcons = {
    Wisdom: Brain,
    Intimacy: Heart,
    GenerationalBridge: Users,
    Presence: Leaf,
    Growth: Rocket,
    Default: Bot,
};

// Activity-specific icons
export const ActivityIcons = {
    Conversation: MessageCircle,
    Home: Home,
    User: User,
    Settings: Settings,
    Book: Book,
    Target: Target,
    TrendingUp: TrendingUp,
    Calendar: Calendar,
    Star: Star,
    Zap: Zap,
    Check: Check,
    X: X,
    Send: Send,
    Bot: Bot,
    Activity: Activity,
    Mic: Mic,
    Volume2: Volume2,
    StopCircle: StopCircle,
    Ellipsis: Ellipsis,
    ChevronRight: ChevronRight,
    MoreHorizontal: MoreHorizontal,
    PanelLeft: PanelLeft,
    ArrowRight: ArrowRight,
    Sparkles: Sparkles,
    Family: Family,
    Baby: Baby,
    UserPlus: UserPlus,
    Share2: Share2,
    Award: Award,
    TrendingDown: TrendingDown,
};

// Status and utility icons
export const UtilityIcons = {
    AlertTriangle: AlertTriangle,
    RefreshCw: RefreshCw,
    Copy: Copy,
    ArrowDown: ArrowDown,
    Trash: Trash,
    Bell: Bell,
    Moon: Moon,
    Sun: Sun,
    Palette: Palette,
    Shield: Shield,
    Lock: Lock,
    Eye: Eye,
    EyeOff: EyeOff,
    Plus: Plus,
    Minus: Minus,
    Edit: Edit,
    Save: Save,
    Upload: Upload,
    Download: Download,
    Search: Search,
    Filter: Filter,
    SortAsc: SortAsc,
    SortDesc: SortDesc,
    Grid: Grid,
    List: List,
    Clock: Clock,
    MapPin: MapPin,
    Phone: Phone,
    Mail: Mail,
    Globe: Globe,
};

// Social media icons
export const SocialIcons = {
    Facebook: Facebook,
    Twitter: Twitter,
    Instagram: Instagram,
    Youtube: Youtube,
    Linkedin: Linkedin,
    Github: Github,
    Slack: Slack,
    Discord: Discord,
    Whatsapp: Whatsapp,
    Telegram: Telegram,
};

// Document and media icons
export const MediaIcons = {
    FileText: FileText,
    Image: Image,
    Video: Video,
    Music: Music,
    Camera: Camera,
};

// Commerce and finance icons
export const CommerceIcons = {
    Gift: Gift,
    ShoppingCart: ShoppingCart,
    CreditCard: CreditCard,
    DollarSign: DollarSign,
    Euro: Euro,
    PoundSterling: PoundSterling,
    IndianRupee: IndianRupee,
    JapaneseYen: JapaneseYen,
    Wallet: Wallet,
    Banknote: Banknote,
    PiggyBank: PiggyBank,
    TrendingUpDown: TrendingUpDown,
};

// Chart and data visualization icons
export const ChartIcons = {
    BarChart: BarChart,
    PieChart: PieChart,
    LineChart: LineChart,
    Database: Database,
    Server: Server,
    Cloud: Cloud,
};

// Device and connectivity icons
export const DeviceIcons = {
    Wifi: Wifi,
    Bluetooth: Bluetooth,
    WifiOff: WifiOff,
    BluetoothOff: BluetoothOff,
    Battery: Battery,
    BatteryCharging: BatteryCharging,
    BatteryFull: BatteryFull,
    BatteryLow: BatteryLow,
    BatteryMedium: BatteryMedium,
    Power: Power,
    PowerOff: PowerOff,
};

// Weather and environment icons
export const WeatherIcons = {
    Lightbulb: Lightbulb,
    LightbulbOff: LightbulbOff,
    Fan: Fan,
    Thermometer: Thermometer,
    Droplets: Droplets,
    Wind: Wind,
    SunDim: SunDim,
    Sunset: Sunset,
    Sunrise: Sunrise,
    MoonStar: MoonStar,
    Stars: Stars,
    CloudRain: CloudRain,
    CloudSnow: CloudSnow,
    CloudLightning: CloudLightning,
    CloudDrizzle: CloudDrizzle,
    CloudFog: CloudFog,
    CloudHail: CloudHail,
    CloudRainWind: CloudRainWind,
    CloudSnowWind: CloudSnowWind,
    CloudLightningRain: CloudLightningRain,
    CloudOff: CloudOff,
    Cloudy: Cloudy,
    PartlyCloudy: PartlyCloudy,
    Sunny: Sunny,
    SunsetSunrise: SunsetSunrise,
    ThermometerSun: ThermometerSun,
    ThermometerSnow: ThermometerSnow,
};

// Wave pattern icons (for family connection visualization)
export const WaveIcons = {
    Waves: Waves,
    WavesLadder: WavesLadder,
    WavesTop: WavesTop,
    WavesBottom: WavesBottom,
    WavesMiddle: WavesMiddle,
    WavesLeft: WavesLeft,
    WavesRight: WavesRight,
    WavesUp: WavesUp,
    WavesDown: WavesDown,
    WavesInOut: WavesInOut,
    WavesLeftRight: WavesLeftRight,
    WavesUpDown: WavesUpDown,
    WavesCircle: WavesCircle,
    WavesSquare: WavesSquare,
    WavesTriangle: WavesTriangle,
    WavesPentagon: WavesPentagon,
    WavesHexagon: WavesHexagon,
    WavesHeptagon: WavesHeptagon,
    WavesOctagon: WavesOctagon,
    WavesStar: WavesStar,
    WavesDiamond: WavesDiamond,
    WavesHeart: WavesHeart,
    WavesSpade: WavesSpade,
    WavesClub: WavesClub,
    WavesPentagram: WavesPentagram,
    WavesHexagram: WavesHexagram,
    WavesHeptagram: WavesHeptagram,
    WavesOctagram: WavesOctagram,
    WavesEnneagram: WavesEnneagram,
    WavesDecagram: WavesDecagram,
    WavesCircleDashed: WavesCircleDashed,
    WavesSquareDashed: WavesSquareDashed,
    WavesTriangleDashed: WavesTriangleDashed,
    WavesPentagonDashed: WavesPentagonDashed,
    WavesHexagonDashed: WavesHexagonDashed,
    WavesHeptagonDashed: WavesHeptagonDashed,
    WavesOctagonDashed: WavesOctagonDashed,
    WavesStarDashed: WavesStarDashed,
    WavesDiamondDashed: WavesDiamondDashed,
    WavesHeartDashed: WavesHeartDashed,
    WavesSpadeDashed: WavesSpadeDashed,
    WavesClubDashed: WavesClubDashed,
    WavesPentagramDashed: WavesPentagramDashed,
    WavesHexagramDashed: WavesHexagramDashed,
    WavesHeptagramDashed: WavesHeptagramDashed,
    WavesOctagramDashed: WavesOctagramDashed,
    WavesEnneagramDashed: WavesEnneagramDashed,
    WavesDecagramDashed: WavesDecagramDashed,
};

// Export all icons for convenience
export {
    Brain,
    Heart,
    Users,
    Leaf,
    Rocket,
    MessageCircle,
    Home,
    User,
    Settings,
    Book,
    Target,
    TrendingUp,
    Calendar,
    Star,
    Zap,
    Check,
    X,
    Send,
    Bot,
    Activity,
    Mic,
    Volume2,
    StopCircle,
    Ellipsis,
    ChevronRight,
    MoreHorizontal,
    PanelLeft,
    ArrowRight,
    Sparkles,
    Family,
    Baby,
    UserPlus,
    Share2,
    Award,
    TrendingDown,
    AlertTriangle,
    RefreshCw,
    Copy,
    ArrowDown,
    Trash,
    Bell,
    Moon,
    Sun,
    Palette,
    Shield,
    Lock,
    Eye,
    EyeOff,
    Plus,
    Minus,
    Edit,
    Save,
    Upload,
    Download,
    Search,
    Filter,
    SortAsc,
    SortDesc,
    Grid,
    List,
    Clock,
    MapPin,
    Phone,
    Mail,
    Globe,
    Facebook,
    Twitter,
    Instagram,
    Youtube,
    Linkedin,
    Github,
    Slack,
    Discord,
    Whatsapp,
    Telegram,
    FileText,
    Image,
    Video,
    Music,
    Camera,
    Gift,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Euro,
    PoundSterling,
    IndianRupee,
    JapaneseYen,
    Wallet,
    Banknote,
    PiggyBank,
    TrendingUpDown,
    BarChart,
    PieChart,
    LineChart,
    Database,
    Server,
    Cloud,
    Wifi,
    Bluetooth,
    WifiOff,
    BluetoothOff,
    Battery,
    BatteryCharging,
    BatteryFull,
    BatteryLow,
    BatteryMedium,
    Power,
    PowerOff,
    Lightbulb,
    LightbulbOff,
    Fan,
    Thermometer,
    Droplets,
    Wind,
    SunDim,
    Sunset,
    Sunrise,
    MoonStar,
    Stars,
    CloudRain,
    CloudSnow,
    CloudLightning,
    CloudDrizzle,
    CloudFog,
    CloudHail,
    CloudRainWind,
    CloudSnowWind,
    CloudLightningRain,
    CloudOff,
    Cloudy,
    PartlyCloudy,
    Sunny,
    SunsetSunrise,
    ThermometerSun,
    ThermometerSnow,
    Waves,
    WavesLadder,
    WavesTop,
    WavesBottom,
    WavesMiddle,
    WavesLeft,
    WavesRight,
    WavesUp,
    WavesDown,
    WavesInOut,
    WavesLeftRight,
    WavesUpDown,
    WavesCircle,
    WavesSquare,
    WavesTriangle,
    WavesPentagon,
    WavesHexagon,
    WavesHeptagon,
    WavesOctagon,
    WavesStar,
    WavesDiamond,
    WavesHeart,
    WavesSpade,
    WavesClub,
    WavesPentagram,
    WavesHexagram,
    WavesHeptagram,
    WavesOctagram,
    WavesEnneagram,
    WavesDecagram,
    WavesCircleDashed,
    WavesSquareDashed,
    WavesTriangleDashed,
    WavesPentagonDashed,
    WavesHexagonDashed,
    WavesHeptagonDashed,
    WavesOctagonDashed,
    WavesStarDashed,
    WavesDiamondDashed,
    WavesHeartDashed,
    WavesSpadeDashed,
    WavesClubDashed,
    WavesPentagramDashed,
    WavesHexagramDashed,
    WavesHeptagramDashed,
    WavesOctagramDashed,
    WavesEnneagramDashed,
    WavesDecagramDashed,
};
