packages:
  - "packages/core"
  - "packages/config"
  - "packages/adapters/*"
  - "packages/clients/*"
  - "packages/plugins/*"
  - "packages/family/*"
  - "packages/blockchain/*"
  - "packages/auth/*"
  - "agent"
  - "client"
  - "packages/create-eliza-app"
  - "packages/_examples/*"
