/**
 * Privacy & Identity commands for Telegram bot.
 * /me, /privacy, /export, /deletedata
 */

import type { Context } from "grammy";
import { InlineKeyboard } from "grammy";
import {
    getUser,
    getUserStats,
    exportUserData,
    deleteUser,
    updateUser,
} from "./userStore.js";
import type { SessionData } from "./handlers.js";

type BotContext = Context & { session: SessionData };

export async function handleMe(ctx: BotContext): Promise<void> {
    const telegramId = ctx.from?.id.toString();
    if (!telegramId) return;

    const stats = getUserStats(telegramId);
    if (!stats) {
        await ctx.reply("I don't have any data for you yet. Send /start to get going!");
        return;
    }

    const user = getUser(telegramId);
    const name = ctx.from?.first_name || ctx.from?.username || "there";
    const joined = new Date(stats.joinedAt).toLocaleDateString("en-GB", {
        day: "numeric", month: "short", year: "numeric",
    });

    const moodSummary = Object.entries(stats.moodBreakdown)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 3)
        .map(([mood, count]) => `${mood}: ${count}`)
        .join(", ");

    const agentLine = user?.preferred_agent
        ? `Active agent: *${user.preferred_agent}*`
        : "No agent selected";

    await ctx.reply(
        `*Hey ${name}!* \u{1F44B}\n\n` +
        `\u{1F4C5} Member since: ${joined}\n` +
        `\u{1F4AC} Check-ins: *${stats.totalCheckins}*\n` +
        `\u{1F525} Current streak: *${stats.currentStreak} day${stats.currentStreak !== 1 ? "s" : ""}*\n` +
        `\u{1F493} People tracked: *${stats.familyMembersCount}*\n` +
        `\u{1F91D} Total connections logged: *${stats.totalInteractions}*\n` +
        `\u{1F916} ${agentLine}\n` +
        (moodSummary ? `\n\u{1F4CA} Top moods: ${moodSummary}\n` : "") +
        `\n_Use /privacy to see data policies, or /export for your data._`,
        { parse_mode: "Markdown" }
    );
}

export async function handlePrivacy(ctx: BotContext): Promise<void> {
    const kb = new InlineKeyboard()
        .text("\u{1F4E6} Export My Data", "privacy:export")
        .row()
        .text("\u{1F5D1}\u{FE0F} Delete All My Data", "privacy:delete_confirm");

    await ctx.reply(
        "*Your Privacy* \u{1F512}\n\n" +
        "*What we store:*\n" +
        "\u{2022} Your Telegram ID and username (for identity)\n" +
        "\u{2022} Check-in history (mood, gratitude entries)\n" +
        "\u{2022} Family members you add and interaction logs\n" +
        "\u{2022} Your preferences (agent, nudge settings)\n\n" +
        "*What we DON'T do:*\n" +
        "\u{2022} We never sell or share your data\n" +
        "\u{2022} We don't use it for ads\n" +
        "\u{2022} We don't store your free-text messages permanently — only check-in responses\n" +
        "\u{2022} AI responses are generated by Fireworks AI — they don't retain your data\n\n" +
        "*Your rights:*\n" +
        "\u{2022} Export all your data anytime\n" +
        "\u{2022} Delete everything with one tap\n" +
        "\u{2022} Pause nudges without losing history\n\n" +
        "_Your data lives on our server in Helsinki. Only you and the bot can access it._",
        { parse_mode: "Markdown", reply_markup: kb }
    );
}

export async function handleExport(ctx: BotContext): Promise<void> {
    const telegramId = ctx.from?.id.toString();
    if (!telegramId) return;

    const data = exportUserData(telegramId);
    if (!data) {
        await ctx.reply("No data found for your account.");
        return;
    }

    const summary = formatExport(data);

    if (summary.length > 4000) {
        // Split into chunks
        const chunks = splitMessage(summary, 4000);
        for (const chunk of chunks) {
            await ctx.reply(chunk, { parse_mode: "Markdown" });
        }
    } else {
        await ctx.reply(summary, { parse_mode: "Markdown" });
    }
}

export async function handleDeleteConfirm(ctx: BotContext): Promise<void> {
    await ctx.answerCallbackQuery();

    const kb = new InlineKeyboard()
        .text("\u{274C} Yes, delete everything", "privacy:delete_final")
        .row()
        .text("\u{2190} Cancel", "privacy:cancel");

    if (ctx.callbackQuery?.message) {
        await ctx.api.editMessageText(
            ctx.callbackQuery.message.chat.id,
            ctx.callbackQuery.message.message_id,
            "*Are you sure?* \u{26A0}\u{FE0F}\n\n" +
            "This will permanently delete:\n" +
            "\u{2022} Your profile and preferences\n" +
            "\u{2022} All check-in history\n" +
            "\u{2022} All family members and connection logs\n\n" +
            "_This cannot be undone._",
            { parse_mode: "Markdown", reply_markup: kb }
        );
    }
}

export async function handleDeleteFinal(ctx: BotContext): Promise<void> {
    await ctx.answerCallbackQuery({ text: "Data deleted" });
    const telegramId = ctx.from?.id.toString();
    if (!telegramId) return;

    deleteUser(telegramId);

    // Reset session
    ctx.session.onboardingComplete = false;
    ctx.session.preferredAgent = undefined;
    ctx.session.checkInStreak = 0;
    ctx.session.lastCheckIn = undefined;
    ctx.session.familyMembers = undefined;
    ctx.session.nudgePaused = false;

    if (ctx.callbackQuery?.message) {
        await ctx.api.editMessageText(
            ctx.callbackQuery.message.chat.id,
            ctx.callbackQuery.message.message_id,
            "*All data deleted.* \u{2705}\n\n" +
            "Your account has been wiped. If you'd like to start fresh, just send /start.\n\n" +
            "_Take care_ \u{1F49B}",
            { parse_mode: "Markdown" }
        );
    }
}

export async function handlePrivacyCancel(ctx: BotContext): Promise<void> {
    await ctx.answerCallbackQuery({ text: "Cancelled" });
    if (ctx.callbackQuery?.message) {
        await ctx.api.editMessageText(
            ctx.callbackQuery.message.chat.id,
            ctx.callbackQuery.message.message_id,
            "\u{2705} _Deletion cancelled. Your data is safe._",
            { parse_mode: "Markdown" }
        );
    }
}

/**
 * First-use privacy disclosure — shown once before any data is stored.
 * Returns true if disclosure was shown (caller should wait for acceptance).
 */
export async function showPrivacyDisclosureIfNeeded(ctx: BotContext): Promise<boolean> {
    const telegramId = ctx.from?.id.toString();
    if (!telegramId) return false;

    const user = getUser(telegramId);
    if (user?.privacy_accepted) return false;

    const kb = new InlineKeyboard()
        .text("\u{2705} Sounds good", "privacy:accept")
        .text("\u{1F4D6} Full details", "privacy:full");

    await ctx.reply(
        "*Quick note on privacy* \u{1F512}\n\n" +
        "I'll remember your check-ins, family connections, and preferences to give you a personalized experience.\n\n" +
        "\u{2022} Your data stays on our server — never sold or shared\n" +
        "\u{2022} You can export or delete everything anytime via /privacy\n" +
        "\u{2022} AI responses are generated externally but your data isn't stored there\n\n" +
        "_Tap below to continue:_",
        { parse_mode: "Markdown", reply_markup: kb }
    );
    return true;
}

export async function handlePrivacyAccept(ctx: BotContext): Promise<void> {
    await ctx.answerCallbackQuery({ text: "Welcome!" });
    const telegramId = ctx.from?.id.toString();
    if (telegramId) {
        updateUser(telegramId, { privacy_accepted: 1 });
    }

    if (ctx.callbackQuery?.message) {
        await ctx.api.editMessageText(
            ctx.callbackQuery.message.chat.id,
            ctx.callbackQuery.message.message_id,
            "\u{2705} _Great! You're all set. Use the menu below or just start chatting._",
            { parse_mode: "Markdown" }
        );
    }
}

// --- Helpers ---

function formatExport(data: ReturnType<typeof exportUserData>): string {
    if (!data) return "No data.";

    const lines: string[] = [
        "*Your Data Export* \u{1F4E6}\n",
        `*Profile*`,
        `Username: ${data.user.username || "not set"}`,
        `Name: ${data.user.first_name || "not set"}`,
        `Joined: ${new Date(data.user.joined_at).toISOString().split("T")[0]}`,
        `Streak: ${data.user.checkin_streak} days`,
        `Agent: ${data.user.preferred_agent || "none"}`,
        "",
    ];

    if (data.checkins.length > 0) {
        lines.push(`*Check-ins* (${data.checkins.length} total)\n`);
        for (const ci of data.checkins.slice(0, 20)) {
            const date = new Date(ci.created_at).toISOString().split("T")[0];
            lines.push(`${date}: ${ci.mood}${ci.gratitude ? ` — "${ci.gratitude}"` : ""}`);
        }
        if (data.checkins.length > 20) {
            lines.push(`_...and ${data.checkins.length - 20} more_`);
        }
        lines.push("");
    }

    if (data.familyMembers.length > 0) {
        lines.push(`*Family Members* (${data.familyMembers.length})\n`);
        for (const fm of data.familyMembers) {
            lines.push(`\u{2022} ${fm.name} (${fm.relationship}) — ${fm.interactions.length} interactions`);
        }
        lines.push("");
    }

    lines.push("_End of export. Use /privacy for deletion options._");
    return lines.join("\n");
}

function splitMessage(text: string, maxLen: number): string[] {
    const chunks: string[] = [];
    let remaining = text;
    while (remaining.length > maxLen) {
        let splitAt = remaining.lastIndexOf("\n", maxLen);
        if (splitAt < maxLen / 2) splitAt = maxLen;
        chunks.push(remaining.substring(0, splitAt));
        remaining = remaining.substring(splitAt);
    }
    if (remaining) chunks.push(remaining);
    return chunks;
}
